<?php

return [
    'name' => 'Paypal',
    'PAYPAL_SENDBOX_CLIENT_ID' => env('PAYPAL_SENDBOX_CLIENT_ID', 'Ab7PORaM7Qu7mQlumVUZn3-HlSFHJks1pcnxnrCALoMiRs0NyrHg02JwbHMf2tsfV_jy1ziLzv5CdB3G'),
    'PAYPAL_SENDBOX_CLIENT_SECRIRT' => env('PAYPAL_SENDBOX_CLIENT_SECRIRT','KtbarnhCk46f0fSrYPrzs89I3dd9ZeUCyGIguy0mfuLcrrwOp0KHcRtKvCi3T0OR2r35plQv76h5L7p'),

    // In production

    'PAYPAL_CLIENT_ID' => env('PAYPAL_CLIENT_ID', 'Ab7PORaM7Qu7mQlumVUZn3-HlSFHJks1pcnxnrCALoMiRs0NyrHg02JwbHMf2tsfV_jy1ziLzv5CdB3G'),
    'PAYPAL_CLIENT_SECRIRT' => env('PAYPAL_CLIENT_SECRIRT','KtbarnhCk46f0fSrYPrzs89I3dd9ZeUCyGIguy0mfuLcrrwOp0KHcRtKvCi3T0OR2r35plQv76h5L7p'),

];
